#!/usr/bin/bash
Tmp="/tmp/$$"
Tmp2="/tmp/$$_$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm -f "$Tmp" >/dev/null 2>&1

# egrep MNEMONIC:: InstructionSet.java |   sed 's/^.*MNEMONIC:: //'   | gawk '{print "" $0}' > mnemonics.txt

egrep MNEMONIC:: InstructionSet.java  | gawk '
 {
     out = ""
     line = $0
     sz = $2
     gsub(/[":]/,"", sz)
     m = sz
     sz = line
     sub(/^.*MNEMONIC::/,"",sz)  
     printf("%-6s    %s\n", m, sz)
 }
 ' > mnemonics.txt





egrep PRAGMA:: HW.java |   sed 's/^.*PRAGMA:: //'   | gawk '{print "" $0}' > pragmas.txt
egrep HELP:: TOY.java |   sed 's/^.*HELP:: //'      > $Tmp

cat $Tmp | gawk -F, ' {
    printf("\"%-8s%-24s\"\n",$1,$2);
} ' > $Tmp2

L=`wc -l $Tmp2 | gawk '{print int(($1/2)+1)}'`
cp $Tmp2 TMP
cd TMP
rm -rf x*
split -l $L $Tmp2
paste xaa xab | sed 's/"//g' > ../help.txt
cd ..
echo "" >> help.txt
echo "Pragmas" >> help.txt
echo "" >> help.txt
cat pragmas.txt  >> help.txt
echo "" >> help.txt
echo "Mnemonics" >> help.txt
echo "" >> help.txt
cat mnemonics.txt  >> help.txt
echo "" >> help.txt
echo "Instructions" >> help.txt
echo "" >> help.txt
cat instructionset.txt >> help.txt
echo "" >> help.txt
