#!/bin/bash
list
genhelp

git add genhelp
git add help.txt
git add H.java
git add ObjectRing.java
git add instructionset.txt
git add ANSI.java
git add Pane.java
git add HW.java
git add TOY.java
git add Finder.java
git add test.toy
git add README.md
git add pushit
git add list
git add repo.txt
git commit -m "Update"
# git tag -a v2.0 -m "First Tagged Version"
git push -u origin main

